/*
 * Copyright 2015 Unicommerce Technologies (P) Limited . All Rights Reserved.
 * UNICOMMERCE TECHONOLOGIES PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * @version     1.0, 5/16/15 3:19 PM
 * @author amdalal
 */

package com.uc.wms.aspect.locking;

public enum Namespace {
    INFLOW_RECEIPT_CODE,

    CHANNEL_INVENTORY_SYNC_DO,
    CHANNEL_ORDER_STATUS_SYNC,
    CHANNEL_PENDING_ORDER_STATUS_SYNC_DO,
    CHANNEL_RETURNED_ORDER_STATUS_SYNC_DO,
    CHANNEL_ORDER_STATUS_SYNC_DO,
    CHANNEL_CATALOG_SYNC_DO,
    CHANNEL_WAREHOUSE_INVENTORY_DO,
    CHANNEL_ORDER_SYNC_DO,
    CHANNEL_RECONCILIATION_INVOICE_SYNC,
    CHANNEL_RECONCILIATION_TRANSACTION_SYNC,
    TENANT,
    SHIPMENT_TRACKING_STATUS_SYNC,
    ACKNOWLEDGE_PENDING_SNAPSHOTS,
    CONTENT,
    PICKER,
    PICKLIST,
    PICK_BUCKET,
    RECONCILIATION,
    TRANSITION,
    SALE_ORDER,
    SALE_ORDER_ITEM,
    ITEM,
    ITEM_TYPE,
    PUTAWAY,
    PURCHASE_ORDER,
    RETURN_MANIFEST,
    MANIFEST,
    JABONG,
    LENSKART_DUAL_COMPANY,
    CHANNEL_PROCESS_PRICE,
    DASHBOARD_WIDGET,
    JOB,
    CACHE_RELOAD,
    CONFIGURATION_RELOAD,
    CHANNEL_FORCE_LOGIN,
    CYCLE_COUNT,
    SHELF,
    SUB_CYCLE_COUNT,
    AUTOCREATE_PICKLIST,
    AUTO_GRN_ITEMS,
    HEALTH_CHECK,
    REVERSE_PICKUP,
    POS,
    BOX,
    PARTY,
    BATCH,
    INVOICE,
    PROCESS_EINVOICE,
    OUTBOUND_GATEPASS,
    SHIPPING_PROVIDER_CONNECTOR,
    SHIPPING_PROVIDER,
    CHANNEL_RECONCILIATION_FILE_DOWNLOAD_SYNC,
    SALE_ORDER_RECONCILIATION,
    RECONCILIATION_ORDER,
    REBATE_ORDER,
    CHANNEL_RECONCILIATION_DATA,
    RATE_CARD,
    REBATE_EVENT,
    SHIPPING_PACKAGE,
    UNIDENTIFIED_TRACKING_NUMBER;
}
